#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__

enum RACE { RACE_PLAYER, RACE_WRIATH, RACE_DEVIL, RACE_SKELETON, RACE_DIABLO, RACE_END };
enum DIRECTION { DIRECTION_UP, DIRECTION_DOWN, DIRECTION_LEFT, DIRECTION_RIGHT, DIRECTION_END };

#endif // !__ENUM_H__
